name: Deploy production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # or your PHP version

    - name: Check for composer changes
      id: composer_changed
      run: |
        if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -qE 'composer\.json|composer\.lock'; then
          echo "COMPOSER_CHANGED=true" >> $GITHUB_ENV
        else
          echo "COMPOSER_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Upload code changes via git-ftp
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: ${{ secrets.FTP_HOST }}
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}

    - name: Install Composer dependencies if needed
      if: env.COMPOSER_CHANGED == 'true'
      run: composer install --no-dev --optimize-autoloader

    - name: Zip vendor folder
      if: env.COMPOSER_CHANGED == 'true'
      run: zip -r vendor.zip vendor

    - name: Upload vendor zip via FTP
      if: env.COMPOSER_CHANGED == 'true'
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PWD }}
        local-dir: vendor.zip
        server-dir: ./
